### ISSUE TITLE
Produce a logo of the software

### ISSUE THREAD

**Issue by MegaMaxim10** [MegaMaxim10/MIUXPhotoCollage#1]

**Comment by andeladenaro** [comment]
Hi.. My name is Andela Denaro, and I want to propose logo for your project. I've seen your other apps, and I think it will be nice if you have one theme of logo. 
Here's my design.

![photo collage](https://user-images.githubusercontent.com/35057858/45877307-932ad700-bdc7-11e8-87c5-3f01908f08a2.png)

I would appreciate hearing your opinion on this. Kind regards.

**Comment by MegaMaxim10** [comment]
I agree with you. You're welcome on board. I hope we produce good results soon.

**Comment by andeladenaro** [comment]
Would you like me to provide the icon files too for this logo?

**Comment by andeladenaro** [comment]
Here's [Google Drive](https://drive.google.com/open?id=1gMz0ziY3Sl_uE1MtfhifgQFud9obuCXj)'s sharing files.

**Comment by MegaMaxim10** [comment]
> 
> 
> Would you like me to provide the icon files too for this logo?

Yes, it will be usefull! Thanks.
